In [1]:
import torch
from Utils import data_generator,mu_orthogonalization

In [2]:
torch.set_default_dtype(torch.float32)

In [3]:
d = 5                   # tensor orde
I = 5               # tensor dimension
r = 2                   # choose tt-rank to be constant
rank = [r] * (d - 1)    # tt-rank
shape = [I] * d 

In [4]:
cores = data_generator(shape, rank)
left_cores = mu_orthogonalization(cores, d)
right_cores = mu_orthogonalization(cores, 0)

In [5]:
for i in range(1, d-1):
    check_core_left = left_cores[i].reshape(-1,left_cores[i].shape[-1])
    print(torch.matmul(check_core_left.T, check_core_left))
    print(torch.allclose(torch.matmul(check_core_left.T, check_core_left), torch.eye(check_core_left.shape[-1]), atol=1e-7))
    check_core_right = right_cores[i].reshape(right_cores[i].shape[0],-1)
    print(torch.matmul(check_core_right, check_core_right.T))
    print(torch.allclose(torch.matmul(check_core_right, check_core_right.T), torch.eye(check_core_right.shape[0]), atol=1e-7))


tensor([[ 1.0000e+00, -3.8364e-08],
        [-3.8364e-08,  1.0000e+00]])
True
tensor([[ 1.0000e+00, -3.0205e-08],
        [-3.0205e-08,  1.0000e+00]])
True
tensor([[1.0000e+00, 9.9180e-09],
        [9.9180e-09, 1.0000e+00]])
True
tensor([[ 1.0000e+00, -2.8156e-08],
        [-2.8156e-08,  1.0000e+00]])
True
tensor([[ 1.0000e+00, -2.7767e-10],
        [-2.7767e-10,  1.0000e+00]])
True
tensor([[1.0000e+00, 2.4546e-08],
        [2.4546e-08, 1.0000e+00]])
True


In [6]:
from Utils import TT_to_tensor

In [7]:
X = TT_to_tensor(rank, cores)
X_left = TT_to_tensor(rank,left_cores)
X_right = TT_to_tensor(rank,right_cores)

In [8]:
print(torch.norm(X - X_left)/torch.norm(X))
print(torch.norm(X - X_right)/torch.norm(X))

tensor(1.9730e-07)
tensor(1.9760e-07)
