In [1]:
import torch
from Utils import data_generator,TT_add,TT_to_tensor,TT_rounding,TT_rounding_2,TTSVD

In [2]:
d = 3                   # tensor orde
I = 5                  # tensor dimension
r = 2                   # choose tt-rank to be constant
                        # need rank to be smaller than I/2, otherwise the mu-orthgonalization will not work
rank = [r] * (d - 1)    # tt-rank
shape = [I] * d 

In [3]:
core1 = data_generator(shape, rank)
core2 = data_generator(shape, rank)

In [4]:
core_add = TT_add(core1,core2)
print(core_add)

[tensor([[ 0.7450, -1.1350,  0.5823,  0.0824],
        [ 1.5693,  1.6467,  0.4622, -1.0243],
        [ 0.1418,  0.7885, -0.3686,  0.3166],
        [-1.1830, -1.3518,  0.9229,  1.6718],
        [-0.1277, -0.3667,  0.3407, -1.0464]]), tensor([[[-1.1204,  0.8124,  0.0000,  0.0000],
         [-0.7321, -1.3289,  0.0000,  0.0000],
         [-0.1623, -0.4065,  0.0000,  0.0000],
         [-0.7022, -1.5691,  0.0000,  0.0000],
         [-0.5699,  1.1415,  0.0000,  0.0000]],

        [[-0.2900,  0.3879,  0.0000,  0.0000],
         [-1.9597, -1.8286,  0.0000,  0.0000],
         [-1.6937,  0.4040,  0.0000,  0.0000],
         [-0.2650, -1.3233,  0.0000,  0.0000],
         [ 0.2512, -1.8635,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000, -0.1618,  1.6381],
         [ 0.0000,  0.0000,  0.6771, -0.0293],
         [ 0.0000,  0.0000, -0.6471, -1.4982],
         [ 0.0000,  0.0000,  0.3895, -1.4652],
         [ 0.0000,  0.0000, -0.7598,  0.5078]],

        [[ 0.0000,  0.0000, -0.4209,  0.1848],
         

In [5]:
X_1 = TT_to_tensor(rank,core1)
X_2 = TT_to_tensor(rank,core2)
X_add = TT_to_tensor([2*r] * (d - 1),core_add)

In [6]:
print(X_1 + X_2)

tensor([[[ 8.5038e-01, -8.2896e-01, -1.7206e-01,  1.4677e+00, -4.6658e-02],
         [ 1.3644e+00,  1.7809e+00,  3.8831e-01, -8.2858e-01,  1.3031e+00],
         [-1.9550e+00,  1.9404e+00, -4.4656e-01, -2.5129e+00,  1.0870e+00],
         [ 1.0083e-01,  2.6302e-01,  4.3553e-01, -5.6767e-01, -4.7997e-01],
         [ 4.3137e+00,  1.1574e+00,  6.9231e-01,  1.8476e+00, -7.7793e-01]],

        [[ 3.5526e+00, -1.5635e+00,  8.1826e-01,  3.1227e+00, -1.5861e+00],
         [-5.7452e+00, -7.2927e+00, -1.4655e+00,  2.7367e+00, -2.5462e+00],
         [-1.1169e+00, -9.0617e-01,  6.9661e-01, -6.0428e-01, -3.5151e+00],
         [-6.9318e+00, -3.1584e+00, -1.1558e+00, -1.6578e+00, -1.2721e+00],
         [-1.6735e+00,  1.1655e-01, -2.1513e+00,  1.2332e+00, -2.0293e-01]],

        [[ 2.9827e-01,  2.8869e-01,  2.2473e-01, -1.6145e-01, -5.8039e-01],
         [-2.3470e+00, -2.0686e+00, -1.6684e-01,  1.0063e-03, -1.3854e+00],
         [ 1.3550e+00, -1.9372e+00,  1.0675e-01,  2.3800e+00, -5.7578e-01],
        

In [7]:
print(X_add)

tensor([[[ 8.5038e-01, -8.2896e-01, -1.7206e-01,  1.4677e+00, -4.6658e-02],
         [ 1.3644e+00,  1.7809e+00,  3.8831e-01, -8.2858e-01,  1.3031e+00],
         [-1.9550e+00,  1.9404e+00, -4.4656e-01, -2.5129e+00,  1.0870e+00],
         [ 1.0083e-01,  2.6302e-01,  4.3553e-01, -5.6767e-01, -4.7997e-01],
         [ 4.3137e+00,  1.1574e+00,  6.9231e-01,  1.8476e+00, -7.7793e-01]],

        [[ 3.5526e+00, -1.5635e+00,  8.1826e-01,  3.1227e+00, -1.5861e+00],
         [-5.7452e+00, -7.2927e+00, -1.4655e+00,  2.7367e+00, -2.5462e+00],
         [-1.1169e+00, -9.0617e-01,  6.9661e-01, -6.0428e-01, -3.5151e+00],
         [-6.9318e+00, -3.1584e+00, -1.1558e+00, -1.6578e+00, -1.2721e+00],
         [-1.6735e+00,  1.1655e-01, -2.1513e+00,  1.2332e+00, -2.0293e-01]],

        [[ 2.9827e-01,  2.8869e-01,  2.2473e-01, -1.6145e-01, -5.8039e-01],
         [-2.3470e+00, -2.0686e+00, -1.6684e-01,  1.0063e-03, -1.3854e+00],
         [ 1.3550e+00, -1.9372e+00,  1.0675e-01,  2.3800e+00, -5.7578e-01],
        

In [8]:
print(torch.norm(X_1 + X_2 - X_add)/torch.norm(X_1 + X_2))

tensor(3.8281e-08)


In [9]:
core_round = TT_rounding(core_add,r)
core_round_2 = TT_rounding_2(core_add,r)

In [10]:
for i in range(d):
    print(core_round[i].shape)
    print(core_round_2[i].shape)

torch.Size([5, 2])
torch.Size([5, 2])
torch.Size([2, 5, 2])
torch.Size([2, 5, 2])
torch.Size([2, 5])
torch.Size([2, 5])


In [11]:
X_round = TT_to_tensor(rank,core_round)
X_round_2 = TT_to_tensor(rank,core_round_2)

In [12]:
print(X_round)

tensor([[[ 0.3832, -0.5639,  0.0263,  0.7119, -0.3296],
         [ 2.0123,  1.6311,  0.5369, -0.2969,  0.5986],
         [-1.9697,  2.0403, -0.2097, -2.9050,  1.2586],
         [ 0.5420,  0.8610,  0.1813, -0.4504,  0.3751],
         [ 2.9632,  0.5981,  0.6340,  1.1476, -0.0334]],

        [[ 3.0591, -1.1949,  0.4971,  2.7773, -0.9537],
         [-5.5645, -7.1466, -1.7138,  3.1376, -2.9923],
         [-1.1976, -1.4190, -0.3585,  0.5706, -0.5836],
         [-6.7394, -3.2937, -1.6099, -0.9113, -0.9047],
         [-1.1680, -0.9672, -0.3134,  0.1903, -0.3578]],

        [[ 0.0907,  0.2751,  0.0417, -0.1905,  0.1292],
         [-2.1959, -2.1056, -0.6142,  0.6102, -0.8184],
         [ 1.3285, -1.7048,  0.1129,  2.2481, -1.0156],
         [-1.2390, -1.0523, -0.3348,  0.2251, -0.3929],
         [-2.3656, -0.5679, -0.5140, -0.8368, -0.0192]],

        [[-2.0975,  0.7184, -0.3496, -1.8156,  0.6027],
         [ 4.4752,  5.5154,  1.3581, -2.3193,  2.2887],
         [ 0.3779,  1.5132,  0.2057, -1.11

In [13]:
print(X_round_2)

tensor([[[ 7.0097e-01, -7.6172e-01,  2.3142e-02,  1.1172e+00, -4.1845e-01],
         [ 1.8658e+00,  1.4885e+00,  5.0300e-01, -2.6231e-01,  5.3708e-01],
         [-2.2321e+00,  2.1442e+00, -1.0900e-01, -3.2986e+00,  1.2004e+00],
         [ 1.5812e-01,  7.4773e-01,  1.2066e-01, -5.9432e-01,  3.3737e-01],
         [ 3.4224e+00,  6.3553e-01,  6.5966e-01,  1.4468e+00,  1.5722e-03]],

        [[ 3.1706e+00, -1.2224e+00,  3.8375e-01,  3.0073e+00, -8.4895e-01],
         [-5.7178e+00, -7.1859e+00, -1.8709e+00,  3.2193e+00, -2.8781e+00],
         [-1.3488e+00, -1.3269e+00, -3.9511e-01,  4.2055e-01, -5.0605e-01],
         [-6.9322e+00, -3.3857e+00, -1.5996e+00, -9.9933e-01, -9.8844e-01],
         [-9.2902e-01, -1.0116e+00, -2.8441e-01,  3.7954e-01, -3.9442e-01]],

        [[ 1.2090e-01,  2.6329e-01,  5.3540e-02, -1.7055e-01,  1.1314e-01],
         [-2.1917e+00, -2.2145e+00, -6.4936e-01,  7.3698e-01, -8.4967e-01],
         [ 1.1680e+00, -1.5877e+00, -1.4158e-03,  2.1547e+00, -8.4679e-01],
        

In [14]:
print(torch.norm(X_round - X_add)/torch.norm(X_add))
print(torch.norm(X_round_2 - X_add)/torch.norm(X_add))

tensor(0.3933)
tensor(0.3883)


#### We have error, this makes sense since TT-rounding is a way of projecting the tensor into the manifold with fixed rank
#### And below we can see that rounding with SVD from left to right is the same as TTSVD
#### But TTSVD does not require orthogonalization from right to left as prestep, GPT says that this step makes sure that SVD can be computed more stable

In [15]:
X_add_proj = TT_to_tensor(rank,TTSVD(X_add,rank))
print(torch.norm(X_add_proj - X_add)/torch.norm(X_add))
print(torch.norm(X_add_proj - X_round)/torch.norm(X_round))

tensor(0.3933)
tensor(1.1079e-06)


In [16]:
print(X_add_proj)

tensor([[[ 0.3832, -0.5639,  0.0263,  0.7119, -0.3295],
         [ 2.0123,  1.6311,  0.5369, -0.2969,  0.5986],
         [-1.9697,  2.0403, -0.2097, -2.9050,  1.2586],
         [ 0.5420,  0.8610,  0.1813, -0.4504,  0.3751],
         [ 2.9632,  0.5981,  0.6340,  1.1476, -0.0334]],

        [[ 3.0591, -1.1949,  0.4971,  2.7773, -0.9537],
         [-5.5645, -7.1466, -1.7138,  3.1376, -2.9923],
         [-1.1976, -1.4190, -0.3585,  0.5706, -0.5836],
         [-6.7394, -3.2937, -1.6099, -0.9113, -0.9047],
         [-1.1680, -0.9672, -0.3134,  0.1903, -0.3578]],

        [[ 0.0907,  0.2751,  0.0417, -0.1905,  0.1292],
         [-2.1959, -2.1056, -0.6142,  0.6102, -0.8184],
         [ 1.3285, -1.7048,  0.1129,  2.2481, -1.0156],
         [-1.2390, -1.0523, -0.3348,  0.2251, -0.3929],
         [-2.3656, -0.5679, -0.5140, -0.8368, -0.0192]],

        [[-2.0975,  0.7184, -0.3496, -1.8155,  0.6027],
         [ 4.4752,  5.5154,  1.3581, -2.3193,  2.2887],
         [ 0.3779,  1.5132,  0.2057, -1.11

#### However, we still have difference between "orthogonalization from left to right and then SVD from right to left" and "orthogonalization from right to left and then SVD from left to right"

Maybe it's because we are truncating the SVD for different matrices/rank in each case. 
TTSVD and the second case are the same since they are truncating the same group of matrices/rank