In [3]:
import torch

In [4]:
X = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(X)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
Y = X

In [6]:
Y[0, 0] = 100

In [7]:
print(X)
print(Y)

tensor([[100,   2],
        [  3,   4],
        [  5,   6]])
tensor([[100,   2],
        [  3,   4],
        [  5,   6]])


In [8]:
X[0,0]=1
print(X)
print(Y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [9]:
Z = X.clone()
Z[0, 0] = 0

In [10]:
print(X)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
print(Z)

tensor([[0, 2],
        [3, 4],
        [5, 6]])


In [12]:
X = X +Z 
print(X)

tensor([[ 1,  4],
        [ 6,  8],
        [10, 12]])


In [13]:
X[0,1]=0
print(X)
print(Z)

tensor([[ 1,  0],
        [ 6,  8],
        [10, 12]])
tensor([[0, 2],
        [3, 4],
        [5, 6]])
